apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-api
  template:
    metadata:
      labels:
        app: pipelines-vote-api
    spec:
      containers:
        - image: quay-gwz7n.apps.cluster-gwz7n.sandbox2622.opentlc.com/quayadmin/pipelines-vote-api:v4
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
